apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "evolution-todo.fullname" . }}-config
  labels:
    {{- include "evolution-todo.labels" . | nindent 4 }}
data:
  BETTER_AUTH_URL: {{ .Values.config.betterAuthUrl | quote }}
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  NEXT_PUBLIC_API_URL: {{ .Values.config.nextPublicApiUrl | quote }}
