apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    {{- include "evolution-todo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  {{- if .Values.frontend.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.frontend.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "evolution-todo.frontend.selectorLabels" . | nindent 4 }}
