apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evolution-todo.fullname" . }}-secrets
  labels:
    {{- include "evolution-todo.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.backend.env.DATABASE_URL | quote }}
  better-auth-secret: {{ .Values.backend.env.BETTER_AUTH_SECRET | quote }}
  openai-api-key: {{ .Values.backend.env.OPENAI_API_KEY | quote }}
